:!sectids:

== Why is this an issue?

Excessive use of nested IF, ELSEIF, or ELSE statements increases cyclomatic complexity and degrades performance.
Using a SWITCH statement or refactoring the code reduces CPU overhead and improves readability.

== Functional rules

- one variable must be used maximum twice in IF / ELSEIF / ELSE statements at the same level - WARNINGs :
- IF and ELSEIF statements use explicitly variable names !
- ELSE statements use implicity variable names !
- one variable must be used maximum twice in IF / ELSEIF / ELSE statements at differents hierarchical levels
- we can assume that if one variable is used three times or more, we should :
- use a SWITCH statement instead
- or refactor the code if possible

== Examples

=== Noncompliant

NON compliant, because `nb` is used 4 times :
- 2 explicit times in IF statements
- 2 implicit times in ELSE statements

[source,java,data-diff-id="1",data-diff-type="noncompliant"]
----
int index = 1;
int nb = 2;
...
if (nb == 0) {
    nb = index;
} else if (nb == 1) {
    nb = index * 2;
} else if (nb == 2) {
    nb = index * 3;
} else {
    nb = -1;
}
return nb;
----

=== Compliant

SWITCH statement solution + refactor solution

[source,java,data-diff-id="1",data-diff-type="compliant"]
----
int index = 1;
int nb = 2;
...
switch (nb) {
    case 0:
    case 1:
    case 2:
        nb = index * (nb + 1);
        break;
    default:
        nb = -1;
}
return nb;
----