name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/**/*.yml'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build
        run: ./mvnw -B install

      - name: Archive rules file
        uses: actions/upload-pages-artifact@v3
        with:
          path: tools/rule-exporter/target/json-file/

  deploy-rules:
    name: Deploy Rules
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: rules
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
